[package]
name = "maple"
version = "0.1.0"
authors = ["Bram Buurlage <brambuurlage@gmail.com>"]
edition = "2018"

[dependencies]
rusttype = { version = "0.9.2", features = ["gpu_cache"] }
image = "0.23.6"
smallvec = "1.4.0"
wgpu = "0.5.0"
zerocopy = "0.3.0"
fnv = "1.0.7"
serde = "1"
ron = "0.6.0"
futures = "0.3"
winit = "0.22.2"
clipboard = "0.4.4"

[dev-dependencies]
pretty_env_logger = "0.4.0"
