[package]
name = "pixel-widgets"
version = "0.1.0"
authors = ["Bram Buurlage <brambuurlage@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Elm inspired UI library styled using images"
license = "MIT"
repository = "https://github.com/Kurble/pixel-widgets"
documentation = "https://docs.rs/pixel-widgets"
keywords = ["gui", "ui", "wgpu", "interface", "graphics", "widgets"]
categories = ["gui"]

[dependencies]
rusttype = { version = "0.9.2", features = ["gpu_cache"] }
image = "0.23.6"
smallvec = "1.4.0"
wgpu = "0.5.0"
zerocopy = "0.3.0"
futures = "0.3"
winit = "0.22.2"
clipboard = "0.4.4"
